import React, { useState } from 'react';
import { 
  Leaf, 
  ArrowRight, 
  Sparkles, 
  BarChart3, 
  Flame, 
  Compass,
  Globe,
  TrendingDown,
  ChevronDown,
  Quote,
  ShieldCheck,
  Star
} from 'lucide-react';

export default function LandingPage({ onStart, hasCalculated }) {
  const [activeFaqIdx, setActiveFaqIdx] = useState(null);

  const stats = [
    { label: "US Footprint Average", value: "16.0 Tons", desc: "per person annually", color: "text-rose-400" },
    { label: "Global Average", value: "4.7 Tons", desc: "per person annually", color: "text-amber-400" },
    { label: "Sustainable Target", value: "2.0 Tons", desc: "needed to halt warming", color: "text-emerald-400" }
  ];

  const features = [
    {
      title: "Interactive Calculator",
      desc: "Analyse your transit, household utilities, flight logs, food habits, and shopping. Get a hyper-precise coefficient analysis.",
      icon: BarChart3,
      glow: "border-emerald-500/20 hover:shadow-emerald-500/5",
      color: "text-emerald-400 bg-emerald-500/10"
    },
    {
      title: "AI Sustainability Coach",
      desc: "Receive 8-10 customized goals generated by our matching engine. Instantly adjust sliders, priority tags, and difficulty coefficients.",
      icon: Sparkles,
      glow: "border-sky-500/20 hover:shadow-sky-500/5",
      color: "text-sky-400 bg-sky-500/10"
    },
    {
      title: "Gamified Eco Quests",
      desc: "Commit to weekly challenges (Zero-Waste, Eco-Commutes). Earn points, level up your profile, and complete targets.",
      icon: Flame,
      glow: "border-amber-500/20 hover:shadow-amber-500/5",
      color: "text-amber-400 bg-amber-500/10"
    },
    {
      title: "Achievements & Badges",
      desc: "Claim metallic badges as your score climb. Lock/Unlock structures show exact quest progressions and level statistics.",
      icon: Compass,
      glow: "border-violet-500/20 hover:shadow-violet-500/5",
      color: "text-violet-400 bg-violet-500/10"
    }
  ];

  const testimonials = [
    {
      quote: "EcoTrack AI completely gamified sustainability for me. Commited to three goals and slashed my carbon score from Carbon Heavy to Eco Explorer!",
      author: "Sarah Jenkins",
      role: "Product Designer, GreenTech",
      avatar: "SJ"
    },
    {
      quote: "The real-time calculator gave me instant feedback on how setting my AC temperature just 2 degrees higher saves 120kg of CO2 per year. Amazing UI!",
      author: "Marcus Vance",
      role: "Climate Researcher",
      avatar: "MV"
    }
  ];

  const faqs = [
    {
      q: "How does EcoTrack AI calculate my carbon footprint?",
      a: "Our calculations utilize verified environmental research emission coefficients. We convert car/bike fuel usages, regional grid mixes (kWh), flight distances, food diets, and plastic generations into precise kilograms of carbon dioxide equivalent (kg CO₂e) per year."
    },
    {
      q: "What are Eco Points used for?",
      a: "Eco Points are gamified reward metrics. Completing weekly challenges (like walking 5km, or taking cold laundry washes) awards points to unlock badges and track your climb from Carbon Heavy to Green Hero."
    },
    {
      q: "Is my personal carbon data secure?",
      a: "Yes! EcoTrack AI respects your privacy. All your calculations, metrics, challenge progress, and goals are stored exclusively in your browser's LocalStorage. No data is sent to external databases."
    }
  ];

  const partners = [
    { name: "GreenCorp", text: "GreenCorp" },
    { name: "EarthGuard", text: "EarthGuard" },
    { name: "EcoNeutral", text: "EcoNeutral" },
    { name: "ClimateFund", text: "ClimateFund" }
  ];

  const toggleFaq = (idx) => {
    setActiveFaqIdx(activeFaqIdx === idx ? null : idx);
  };

  return (
    <div className="py-2 space-y-24">
      
      {/* 1. Hero Section */}
      <section className="text-center max-w-4xl mx-auto px-4 mt-8 md:mt-16 flex flex-col items-center relative z-10">
        
        {/* Pulsing Tagline badge */}
        <div className="inline-flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/25 px-4.5 py-1.5 rounded-full text-xs md:text-sm font-bold text-emerald-400 mb-6 shadow-lg shadow-emerald-500/5 animate-pulse">
          <Sparkles className="w-3.5 h-3.5" />
          <span>Next-Gen Sustainability Engine</span>
        </div>

        <h1 className="text-4xl sm:text-5xl md:text-7xl font-extrabold tracking-tight leading-tight mb-6">
          Track, Understand, and{' '}
          <span className="bg-gradient-to-r from-emerald-400 via-emerald-300 to-sky-400 bg-clip-text text-transparent">
            Reduce Your Footprint
          </span>
        </h1>

        <p className="text-sm sm:text-base md:text-lg text-slate-400 max-w-2xl mb-10 leading-relaxed font-medium">
          EcoTrack AI delivers real-time coefficients calculation, gamified habits quests, and personalized plans to help you lead a sustainable carbon lifestyle.
        </p>

        <div className="flex flex-col sm:flex-row gap-4.5 justify-center items-center w-full sm:w-auto">
          <button
            onClick={() => onStart('calculator')}
            className="w-full sm:w-auto flex items-center justify-center gap-2 bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 font-black px-8 py-4.5 rounded-xl shadow-lg shadow-emerald-500/20 hover:shadow-emerald-500/35 transition-all duration-300 transform hover:-translate-y-0.5"
          >
            {hasCalculated ? 'Go to Calculator' : 'Compute Carbon Score'}
            <ArrowRight className="w-5.5 h-5.5 text-slate-950" />
          </button>
          
          {hasCalculated && (
            <button
              onClick={() => onStart('dashboard')}
              className="w-full sm:w-auto flex items-center justify-center gap-2 bg-slate-900/50 hover:bg-slate-900 border border-white/5 text-slate-200 font-bold px-8 py-4.5 rounded-xl transition-all"
            >
              Enter Dashboard
            </button>
          )}
        </div>
      </section>

      {/* 2. CSS Dashboard Preview Mockup */}
      <section className="max-w-5xl mx-auto px-4 relative">
        <div className="absolute inset-0 bg-emerald-500/5 rounded-[40px] filter blur-3xl pointer-events-none"></div>
        <div className="glass-card border border-white/10 rounded-[32px] p-4 md:p-6 shadow-2xl relative overflow-hidden animate-float">
          {/* Header Mockup */}
          <div className="flex justify-between items-center border-b border-white/5 pb-4 mb-4.5">
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-rose-500"></span>
              <span className="w-3 h-3 rounded-full bg-amber-500"></span>
              <span className="w-3 h-3 rounded-full bg-emerald-500"></span>
            </div>
            <span className="text-[10px] text-slate-500 uppercase tracking-widest font-bold">EcoTrack AI Simulator View</span>
          </div>
          
          {/* Dashboard contents representation */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-slate-950/60 border border-white/5 rounded-2xl p-4.5 text-center flex flex-col items-center">
              <span className="text-[9px] text-slate-500 uppercase font-semibold">Climate Index</span>
              <div className="w-16 h-16 rounded-full border-4 border-emerald-500/20 border-t-emerald-500 flex items-center justify-center my-2">
                <span className="text-lg font-black text-white">82</span>
              </div>
              <span className="text-[10px] font-extrabold text-emerald-400">Eco Champion</span>
            </div>
            <div className="bg-slate-950/60 border border-white/5 rounded-2xl p-4.5 flex flex-col justify-between">
              <span className="text-[9px] text-slate-500 uppercase font-semibold">Annual Footprint</span>
              <span className="text-3xl font-black text-sky-400 my-2">3.4 Tons</span>
              <span className="text-[9px] text-slate-400 leading-tight">60% below US Average</span>
            </div>
            <div className="bg-slate-950/60 border border-white/5 rounded-2xl p-4.5 space-y-2">
              <span className="text-[9px] text-slate-500 uppercase font-semibold">Quests Completed</span>
              <div className="flex items-center justify-between text-xs text-slate-200 border-b border-white/5 pb-1 mt-1">
                <span>Zero Waste Day</span>
                <span className="text-emerald-400 font-bold">Done</span>
              </div>
              <div className="flex items-center justify-between text-xs text-slate-200">
                <span>Eco Commuter</span>
                <span className="text-slate-500">Active</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3. Partners Logo Banner */}
      <section className="max-w-5xl mx-auto px-4 text-center">
        <span className="text-[10px] text-slate-500 uppercase tracking-widest font-extrabold block mb-6">Recognized by Climate Leaders</span>
        <div className="flex flex-wrap justify-center items-center gap-10 md:gap-16">
          {partners.map((p, idx) => (
            <div key={idx} className="flex items-center gap-2 grayscale opacity-30 hover:grayscale-0 hover:opacity-75 transition-all cursor-pointer">
              <ShieldCheck className="w-5 h-5 text-slate-400" />
              <span className="font-extrabold text-sm md:text-base text-slate-400">{p.text}</span>
            </div>
          ))}
        </div>
      </section>

      {/* 4. Features Grid */}
      <section className="max-w-5xl mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-extrabold text-white mb-4">Startup-Grade Features</h2>
          <p className="text-sm md:text-base text-slate-400 max-w-lg mx-auto font-medium">
            Everything you need to turn sustainability targets into daily habits.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {features.map((f, idx) => {
            const Icon = f.icon;
            return (
              <div 
                key={idx} 
                className={`glass-card glass-card-hover border ${f.glow} rounded-3xl p-6 md:p-8 flex gap-5 items-start relative group`}
              >
                <div className={`${f.color} p-3.5 rounded-2xl border border-white/5 flex-shrink-0`}>
                  <Icon className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg md:text-xl font-bold text-white mb-2">{f.title}</h3>
                  <p className="text-xs md:text-sm text-slate-400 leading-relaxed font-medium">{f.desc}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* 5. Testimonial Section */}
      <section className="max-w-5xl mx-auto px-4 grid grid-cols-1 md:grid-cols-2 gap-8">
        {testimonials.map((t, idx) => (
          <div key={idx} className="glass-card border border-white/5 p-6 md:p-8 rounded-3xl relative flex flex-col justify-between">
            <Quote className="absolute top-6 right-6 w-10 h-10 text-emerald-500/10 pointer-events-none" />
            <p className="text-xs md:text-sm text-slate-300 leading-relaxed mb-6 font-medium italic">
              "{t.quote}"
            </p>
            <div className="flex items-center gap-3.5 border-t border-white/5 pt-4">
              <div className="w-10 h-10 rounded-full bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center font-black text-xs text-emerald-400">
                {t.avatar}
              </div>
              <div>
                <h4 className="font-bold text-white text-xs md:text-sm">{t.author}</h4>
                <span className="text-[10px] text-slate-500">{t.role}</span>
              </div>
            </div>
          </div>
        ))}
      </section>

      {/* 6. Accordion FAQs */}
      <section className="max-w-4xl mx-auto px-4">
        <h2 className="text-2xl md:text-4xl font-extrabold text-white text-center mb-10">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {faqs.map((faq, idx) => {
            const isOpen = activeFaqIdx === idx;
            return (
              <div key={idx} className="glass-card border border-white/5 rounded-2xl overflow-hidden transition-all duration-300">
                <button
                  onClick={() => toggleFaq(idx)}
                  className="w-full flex justify-between items-center p-5 text-left font-bold text-sm md:text-base text-white hover:text-emerald-400 transition-colors"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-5 h-5 text-slate-400 transition-transform duration-300 ${isOpen ? 'transform rotate-180 text-emerald-400' : ''}`} />
                </button>
                {isOpen && (
                  <div className="px-5 pb-5 text-xs md:text-sm text-slate-400 leading-relaxed border-t border-white/5 pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* 7. Call To Action Footer Banner */}
      <section className="max-w-5xl mx-auto px-4 pb-12">
        <div className="glass-card border border-emerald-500/25 bg-emerald-950/20 rounded-[36px] p-8 md:p-14 text-center flex flex-col items-center relative overflow-hidden">
          <div className="absolute inset-0 bg-emerald-500/5 filter blur-2xl pointer-events-none"></div>
          
          <Globe className="w-12 h-12 text-emerald-400 mb-6 animate-pulse" />
          
          <h2 className="text-2xl md:text-4xl font-black text-white mb-3">
            Ready to offset your carbon imprint?
          </h2>
          <p className="text-xs md:text-sm text-slate-300 max-w-lg mb-8 leading-relaxed font-medium">
            Join thousands of active eco-citizens taking action, setting targets, and earning points. Start your analysis right now.
          </p>
          
          <button
            onClick={onStart}
            className="flex items-center gap-2 bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 font-black px-7 py-4 rounded-xl shadow-lg transition-all"
          >
            <span>Get Started Free</span>
            <TrendingDown className="w-4 h-4 text-slate-950" />
          </button>
        </div>
      </section>

    </div>
  );
}
